### ISSUE TITLE
Cannot render nested components

### ISSUE THREAD

**Issue by NathanielHill** [lukechilds/react-jsdom#9]
This package would be great as a simpler alternative to rolling your own React/JSDOM SSR renderer, except that it only returns the first child and therefore can't render multiple/nested components.

https://github.com/lukechilds/react-jsdom/blob/3f3779f289aeb6fc3c644a09cdc5a6b32975fd96/src/index.js#L29

Is there a reason for this @lukechilds ?

**Comment by NathanielHill** [comment]
Personally, I'm interested in `container.innerHTML`, but I suppose you could also export the container element itself, or an array of it's child elements?

**Comment by lukechilds** [comment]
I wrote this before it was possible to export multiple sibling components.

I would accept a PR that enables this.

It should return either an element or a node list, not the container or an HTML string.

**Comment by NathanielHill** [comment]
Ok, unfortunately at the moment I'm having bundling issues with `jsdom` (https://github.com/zeit/ncc/issues/274) and I've had to use my own patched version of `jsdom`.

I will come back to this when my upstream issues are fixed and I can actually use this package.

Will submit a PR then :+1:

**Comment by franciscop** [comment]
I can work on this as noted in #10 and this will almost for sure be a breaking change. I'll submit this with docs and tests, thanks!

**Comment by NathanielHill** [comment]
@franciscop Awesome, great work!
@lukechilds Okay, closing :+1:

**Comment by franciscop** [comment]
Wait that doesn't solve this issue, but I'm creating a new PR solving this issue 👍

**Comment by franciscop** [comment]
Here it is: https://github.com/lukechilds/react-jsdom/pull/11
